/// Export engine for rendering secrets in various output formats.
///
/// Supports dotenv, direnv, JSON, YAML, and shell formats. Each format
/// handles quoting and escaping appropriate to its conventions.
use crate::cli::ExportFormat;

/// Renders secrets as a formatted string in the specified export format.
///
/// The `env_name` is used in header comments for text-based formats.
/// Secrets are rendered in the order provided.
pub fn render(format: &ExportFormat, env_name: &str, secrets: &[(String, String)]) -> String {
    match format {
        ExportFormat::Dotenv => render_dotenv(env_name, secrets),
        ExportFormat::Direnv => render_direnv(env_name, secrets),
        ExportFormat::Shell => render_shell(env_name, secrets),
        ExportFormat::Json => render_json(secrets),
        ExportFormat::Yaml => render_yaml(env_name, secrets),
    }
}

/// Generates header comment lines for text-based formats.
fn header(env_name: &str, format_name: &str) -> String {
    format!(
        "# Generated by zuul — environment: {env_name}\n\
         # Do not edit manually. Re-export with: zuul export --env {env_name} --export-format {format_name}\n"
    )
}

/// Renders secrets in a shell-like key=value format.
///
/// This is the shared implementation for dotenv, direnv, and shell formats.
/// The `prefix` is prepended to each line (e.g., `"export "` for direnv).
/// The `escape_fn` handles value escaping, and `quote` is the quote character.
fn render_kv(
    env_name: &str,
    format_name: &str,
    secrets: &[(String, String)],
    prefix: &str,
    quote: char,
    escape_fn: fn(&str) -> String,
) -> String {
    let mut out = header(env_name, format_name);
    for (key, value) in secrets {
        out.push('\n');
        out.push_str(prefix);
        out.push_str(key);
        out.push('=');
        out.push(quote);
        out.push_str(&escape_fn(value));
        out.push(quote);
    }
    out.push('\n');
    out
}

/// Renders secrets in dotenv format (`KEY="value"`).
fn render_dotenv(env_name: &str, secrets: &[(String, String)]) -> String {
    render_kv(env_name, "dotenv", secrets, "", '"', escape_double_quote)
}

/// Renders secrets in direnv format (`export KEY='value'`).
fn render_direnv(env_name: &str, secrets: &[(String, String)]) -> String {
    render_kv(
        env_name,
        "direnv",
        secrets,
        "export ",
        '\'',
        escape_single_quote,
    )
}

/// Renders secrets in shell format (`KEY='value'`).
fn render_shell(env_name: &str, secrets: &[(String, String)]) -> String {
    render_kv(env_name, "shell", secrets, "", '\'', escape_single_quote)
}

/// Escapes a value for double-quoted strings (dotenv).
///
/// Escapes backslashes, double quotes, dollar signs, and newlines.
fn escape_double_quote(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '$' => escaped.push_str("\\$"),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            _ => escaped.push(ch),
        }
    }
    escaped
}

/// Escapes single quotes for shell single-quoted strings.
///
/// Replaces `'` with `'\''` (end quote, literal quote, restart quote).
fn escape_single_quote(value: &str) -> String {
    value.replace('\'', "'\\''")
}

/// Renders secrets as a JSON object.
///
/// No header comment (not valid JSON). Uses `serde_json` for correct escaping.
fn render_json(secrets: &[(String, String)]) -> String {
    let map: serde_json::Map<String, serde_json::Value> = secrets
        .iter()
        .map(|(k, v)| (k.clone(), serde_json::Value::String(v.clone())))
        .collect();
    let mut out = serde_json::to_string_pretty(&map).unwrap_or_else(|_| "{}".to_string());
    out.push('\n');
    out
}

/// Renders secrets in YAML format.
///
/// Values are always double-quoted for safety (handles special chars and multiline).
fn render_yaml(env_name: &str, secrets: &[(String, String)]) -> String {
    let mut out = header(env_name, "yaml");
    for (key, value) in secrets {
        out.push('\n');
        out.push_str(key);
        out.push_str(": \"");
        out.push_str(&escape_yaml(value));
        out.push('"');
    }
    out.push('\n');
    out
}

/// Escapes a value for YAML double-quoted strings.
///
/// Escapes backslashes, double quotes, and newlines.
fn escape_yaml(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            _ => escaped.push(ch),
        }
    }
    escaped
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_secrets() -> Vec<(String, String)> {
        vec![
            (
                "DATABASE_URL".to_string(),
                "postgres://localhost:5432/mydb".to_string(),
            ),
            ("API_KEY".to_string(), "sk_test_abc123".to_string()),
        ]
    }

    // --- dotenv ---

    #[test]
    fn dotenv_basic() {
        let out = render(&ExportFormat::Dotenv, "dev", &sample_secrets());
        assert!(out.contains("DATABASE_URL=\"postgres://localhost:5432/mydb\""));
        assert!(out.contains("API_KEY=\"sk_test_abc123\""));
    }

    #[test]
    fn dotenv_header() {
        let out = render(&ExportFormat::Dotenv, "dev", &[]);
        assert!(out.contains("# Generated by zuul — environment: dev"));
        assert!(out.contains("--export-format dotenv"));
    }

    #[test]
    fn dotenv_multiline() {
        let secrets = vec![("CERT".to_string(), "line1\nline2\nline3".to_string())];
        let out = render(&ExportFormat::Dotenv, "dev", &secrets);
        assert!(out.contains("CERT=\"line1\\nline2\\nline3\""));
    }

    #[test]
    fn dotenv_special_chars() {
        let secrets = vec![(
            "VAL".to_string(),
            "has \"quotes\" and $vars and \\slashes".to_string(),
        )];
        let out = render(&ExportFormat::Dotenv, "dev", &secrets);
        assert!(out.contains(r#"VAL="has \"quotes\" and \$vars and \\slashes""#));
    }

    #[test]
    fn dotenv_empty_value() {
        let secrets = vec![("EMPTY".to_string(), String::new())];
        let out = render(&ExportFormat::Dotenv, "dev", &secrets);
        assert!(out.contains("EMPTY=\"\""));
    }

    #[test]
    fn dotenv_carriage_return() {
        let secrets = vec![("CR".to_string(), "line1\r\nline2".to_string())];
        let out = render(&ExportFormat::Dotenv, "dev", &secrets);
        assert!(out.contains("CR=\"line1\\r\\nline2\""));
    }

    // --- direnv ---

    #[test]
    fn direnv_basic() {
        let out = render(&ExportFormat::Direnv, "staging", &sample_secrets());
        assert!(out.contains("export DATABASE_URL='postgres://localhost:5432/mydb'"));
        assert!(out.contains("export API_KEY='sk_test_abc123'"));
    }

    #[test]
    fn direnv_header() {
        let out = render(&ExportFormat::Direnv, "staging", &[]);
        assert!(out.contains("# Generated by zuul — environment: staging"));
        assert!(out.contains("--export-format direnv"));
    }

    #[test]
    fn direnv_single_quote_in_value() {
        let secrets = vec![("MSG".to_string(), "it's a test".to_string())];
        let out = render(&ExportFormat::Direnv, "dev", &secrets);
        assert!(out.contains("export MSG='it'\\''s a test'"));
    }

    #[test]
    fn direnv_multiline() {
        let secrets = vec![("CERT".to_string(), "line1\nline2".to_string())];
        let out = render(&ExportFormat::Direnv, "dev", &secrets);
        assert!(out.contains("export CERT='line1\nline2'"));
    }

    #[test]
    fn direnv_empty_value() {
        let secrets = vec![("EMPTY".to_string(), String::new())];
        let out = render(&ExportFormat::Direnv, "dev", &secrets);
        assert!(out.contains("export EMPTY=''"));
    }

    // --- shell ---

    #[test]
    fn shell_basic() {
        let out = render(&ExportFormat::Shell, "dev", &sample_secrets());
        assert!(out.contains("DATABASE_URL='postgres://localhost:5432/mydb'"));
        assert!(out.contains("API_KEY='sk_test_abc123'"));
        // No line should start with "export " (header comments may contain the word)
        for line in out.lines() {
            assert!(
                !line.starts_with("export "),
                "Shell format must not use 'export' keyword: {line}"
            );
        }
    }

    #[test]
    fn shell_header() {
        let out = render(&ExportFormat::Shell, "dev", &[]);
        assert!(out.contains("# Generated by zuul — environment: dev"));
        assert!(out.contains("--export-format shell"));
    }

    #[test]
    fn shell_single_quote_in_value() {
        let secrets = vec![("MSG".to_string(), "it's a test".to_string())];
        let out = render(&ExportFormat::Shell, "dev", &secrets);
        assert!(out.contains("MSG='it'\\''s a test'"));
    }

    #[test]
    fn shell_empty_value() {
        let secrets = vec![("EMPTY".to_string(), String::new())];
        let out = render(&ExportFormat::Shell, "dev", &secrets);
        assert!(out.contains("EMPTY=''"));
    }

    // --- json ---

    #[test]
    fn json_basic() {
        let out = render(&ExportFormat::Json, "dev", &sample_secrets());
        let parsed: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(parsed["DATABASE_URL"], "postgres://localhost:5432/mydb");
        assert_eq!(parsed["API_KEY"], "sk_test_abc123");
    }

    #[test]
    fn json_no_header() {
        let out = render(&ExportFormat::Json, "dev", &sample_secrets());
        assert!(!out.contains("# Generated by zuul"));
    }

    #[test]
    fn json_multiline() {
        let secrets = vec![("CERT".to_string(), "line1\nline2".to_string())];
        let out = render(&ExportFormat::Json, "dev", &secrets);
        let parsed: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(parsed["CERT"], "line1\nline2");
    }

    #[test]
    fn json_empty() {
        let out = render(&ExportFormat::Json, "dev", &[]);
        let parsed: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(parsed, serde_json::json!({}));
    }

    #[test]
    fn json_special_chars() {
        let secrets = vec![(
            "VAL".to_string(),
            "has \"quotes\" and \\slashes".to_string(),
        )];
        let out = render(&ExportFormat::Json, "dev", &secrets);
        let parsed: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(parsed["VAL"], "has \"quotes\" and \\slashes");
    }

    // --- yaml ---

    #[test]
    fn yaml_basic() {
        let out = render(&ExportFormat::Yaml, "prod", &sample_secrets());
        assert!(out.contains("DATABASE_URL: \"postgres://localhost:5432/mydb\""));
        assert!(out.contains("API_KEY: \"sk_test_abc123\""));
    }

    #[test]
    fn yaml_header() {
        let out = render(&ExportFormat::Yaml, "prod", &[]);
        assert!(out.contains("# Generated by zuul — environment: prod"));
        assert!(out.contains("--export-format yaml"));
    }

    #[test]
    fn yaml_multiline() {
        let secrets = vec![("CERT".to_string(), "line1\nline2".to_string())];
        let out = render(&ExportFormat::Yaml, "dev", &secrets);
        assert!(out.contains("CERT: \"line1\\nline2\""));
    }

    #[test]
    fn yaml_special_chars() {
        let secrets = vec![(
            "VAL".to_string(),
            "has \"quotes\" and \\slashes".to_string(),
        )];
        let out = render(&ExportFormat::Yaml, "dev", &secrets);
        assert!(out.contains(r#"VAL: "has \"quotes\" and \\slashes""#));
    }

    #[test]
    fn yaml_empty_value() {
        let secrets = vec![("EMPTY".to_string(), String::new())];
        let out = render(&ExportFormat::Yaml, "dev", &secrets);
        assert!(out.contains("EMPTY: \"\""));
    }

    #[test]
    fn yaml_tab_in_value() {
        let secrets = vec![("TAB".to_string(), "col1\tcol2".to_string())];
        let out = render(&ExportFormat::Yaml, "dev", &secrets);
        assert!(out.contains("TAB: \"col1\\tcol2\""));
    }

    // --- cross-format ---

    #[test]
    fn all_formats_handle_empty_secrets_list() {
        for format in &[
            ExportFormat::Dotenv,
            ExportFormat::Direnv,
            ExportFormat::Shell,
            ExportFormat::Json,
            ExportFormat::Yaml,
        ] {
            let out = render(format, "dev", &[]);
            assert!(!out.is_empty(), "Format {format:?} produced empty output");
        }
    }
}
